CREATE TABLE IF NOT EXISTS tusuarios
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ativo character(1),
    login character varying(20),
    senha character varying(20),
    nome character varying(50),
    email character varying(100),
    data_alteracao timestamp without time zone DEFAULT now(),
	data_cadastro timestamp without time zone DEFAULT now(),
    id_externo character varying(255),

    CONSTRAINT tusuarios_pkey PRIMARY KEY (id)
        
  
)